allowBuilds:
  sharp: set this to true or false
  unrs-resolver: set this to true or false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
overrides:
  nanoid: ^3.3.18
  postcss: ^8.5.23
  sharp: ^0.35.0
